name: Java CI with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build Maven project
        working-directory: ./food-delivery-app-1/order-service
        run: mvn -B package

      - name: Update dependency graph (optional)
        uses: advanced-security/maven-dependency-submission-action@v4
        with:
          directory: ./food-delivery-app-1/order-service
